theme: jekyll-theme-minimal
title: Web Dev Apprentice Curriclum
description: Lesson outlines and resources for the main group training sessions and workshops
logo: /assets/img/WDA_Logo.png
show_downloads: false
