theme: jekyll-theme-minimal
title: Web Dev Apprentice Curriclum
description: Lesson outlines and resources for the main group training sessions and workshops
logo: /assets/css/logo.png
show_downloads: false
